Repository thdwlsgus0/algo_spot, pull requests merged in 2021-11, with the labels that each got.

#42 10월 4주차 알고리즘 문제풀이입니다.
  진현/11주차/괄호회전하기.js
  진현/11주차/수식최대화.js
Labels: 보통

#44 10월 4주차 알고리즘 문제 풀이 입니다.
  juyeong/[2021카카오]메뉴리뉴얼.js
  juyeong/[월간코드챌린지]괄호회전하기.js
  juyeong/[카카오인턴]수식 최대화.js
Labels: 보통

#43 10월 4주차 알고리즘 문제풀이입니다.
  김동용_kingyong9169/[PG]2021 우테코 데모.js
  김동용_kingyong9169/[PG]거리두기 확인하기.js
  김동용_kingyong9169/[PG]괄호 회전하기.js
  김동용_kingyong9169/[PG]교점에 별 만들기.js
  김동용_kingyong9169/[PG]수식 최대화.js
  김동용_kingyong9169/[PG]짝수와 홀수.js
  김동용_kingyong9169/[PG]평균 구하기.js
Labels: 보통

#46 11월 1주차 알고리즘 문제풀이입니다.
  김동용_kingyong9169/[PG]압축.js
  김동용_kingyong9169/[PG]이진 변환 반복하기.js
  김동용_kingyong9169/[PG]튜플.js
Labels: 보통

#45 11월 1주차 알고리즘 문제풀이입니다
  진현/12주차/[3차] 압축.js
  진현/12주차/튜플.js
Labels: 보통

#47 11월 2주차 알고리즘 문제풀이입니다.
  진현/13주차/올바른괄호.js
  진현/13주차/이진변환반복하기.js
Labels: 쉬움

#48 11월 2주차 알고리즘 문제풀이입니다.
  김동용_kingyong9169/[PG]올바른 괄호.js
  김동용_kingyong9169/[PG]후보키.js
Labels: 쉬움

#50 11월 2주차 알고리즘 문제풀이입니다.
  juyeong/[2019 카카오개발자]튜플.js
  juyeong/[연습문제]올바른괄호.js
  juyeong/[월간코드챌린지]이진변환 반복하기.js
Labels: 쉬움

#51 11월 3주차 알고리즘 문제풀이입니다.
  진현/14주차/로또의 최고 순위와 최저 순위.js
  진현/14주차/멀쩡한사각형.js
  진현/14주차/큰수만들기.js
Labels: 쉬움

#53 11월 3주차 알고리즘 문제풀이 입니다.
  juyeong/[2019 카카오 블라인드][3차]압축.js
  juyeong/[2021 Dev]로또의 최고 순위와 최저 순위.js
  juyeong/[sw2019]멀쩡한 사각형.js
  juyeong/[연습문제]다음 큰 숫자.js
  juyeong/[탐욕법]구명보트.js
  juyeong/[탐욕법]큰 수 만들기.js
Labels: 보통

#55 11월 3주차 알고리즘 문제풀이입니다.
  김동용_kingyong9169/[PG]구명보트.js
  김동용_kingyong9169/[PG]로또의 최고 순위와 최저 순위.js
  김동용_kingyong9169/[PG]멀쩡한 사각형.js
  김동용_kingyong9169/[PG]큰 수 만들기.js
  김동용_kingyong9169/[PG]폰켓몬.js
Labels: 어려움
