Repository thdwlsgus0/algo_spot, pull requests merged in 2021-09, with the labels that each got.

#26 9월 1주차 알고리즘 문제풀이입니다.
  진현/7주차/H-Index.js
  진현/7주차/문자열압축.js
  진현/7주차/캐시.js
  진현/7주차/콜라츠추측.js
Labels: 보통

#28 9월 1주차 알고리즘 문제풀이입니다.
  김동용_kingyong9169/[PG]H-index.js
  김동용_kingyong9169/[PG]문자열 압축.js
  김동용_kingyong9169/[PG]캐시.js
  김동용_kingyong9169/[PG]콜라츠 추측.js
Labels: 리팩토링

#29 9월 1주차 알고리즘 풀이입니다.
  juyeong/[2018카카오]캐시.js
  juyeong/[2020카카오]문자열압축.js
  juyeong/[연습]콜라츠추측.js
  juyeong/[정렬]H-index.js
Labels: 보통, 리팩토링

#30 8주차 알고리즘 문제 풀이
  진현/8주차/거리두기확인하기.js
  진현/8주차/메뉴리뉴얼.js
Labels: 보통

#31 9월 2주차 알고리즘 풀이
  juyeong/[2021카카오]메뉴리뉴얼.js
  juyeong/[2021카카오채용연계]거리두기 확인.js
  juyeong/[카카오]키패드.js
Labels: 어려움

#35 9월 3주차 추석 알고리즘 문제 풀이입니다.
  juyeong/[연습문제]N개의최소공배수.js
  juyeong/[연습문제]최댓값과 최솟값.js
Labels: 쉬움

#34 9월 1주차, 3주차 알고리즘 풀이입니다.
  김동용_kingyong9169/[PG]N개의 최소공배수.js
  김동용_kingyong9169/[PG]메뉴 리뉴얼.js
  김동용_kingyong9169/[PG]최댓값과 최솟값.js
Labels: 어려움
